name: fl_umeng_link
description: Umeng link plugin for flutter, only Android and IOS are supported
version: 0.5.0
repository: https://github.com/Wayaer/fl_umeng/tree/main/fl_umeng_link

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  fl_umeng: ^3.7.0

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: fl.umeng.link
        pluginClass: UMengLinkPlugin
      ios:
        pluginClass: UMengLinkPlugin
