name: umeng
description: A new Flutter project.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:

  fl_umeng:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
