name: fl_umeng_apm
description: umeng apm plugin for flutter, only Android and IOS are supported
version: 0.5.0
repository: https://github.com/Wayaer/fl_umeng/tree/main/fl_umeng_apm

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  fl_umeng: ^3.6.0

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:

  plugin:
    platforms:
      android:
        package: fl.umeng.apm
        pluginClass: UMengAPMPlugin
      ios:
        pluginClass: UMengAPMPlugin
