name: fl_umeng_apm
description: umeng apm plugin for flutter, only Android and IOS are supported
version: 1.0.1
repository: https://github.com/Wayaer/fl_umeng/tree/main/fl_umeng_apm

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter
  fl_umeng: ^4.0.1

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: fl.umeng.apm
        pluginClass: UMengAPMPlugin
      ios:
        pluginClass: UMengAPMPlugin
