name: fl_umeng
description: umeng plugin for flutter, only Android and IOS are supported
version: 3.6.0
repository: https://github.com/Wayaer/fl_umeng/tree/main/fl_umeng

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: fl.umeng
        pluginClass: UMengPlugin
      ios:
        pluginClass: UMengPlugin
