name: example
description: Demonstrates how to use the fl_umeng_link plugin.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  fl_umeng_link:
    path: ../

dev_dependencies:
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
